version: "3.7"

services:
  genius-top10:
    build: ./
    command: python src/app.py
    container_name: genius_top10
    ports:
      - "8080:8080"
    volumes:
      - ./:/code
    depends_on:
      - redis
    env_file: ./.env
    stdin_open: true
    tty: true

  redis:
    image: redis:alpine
    command: redis-server
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/var/lib/postgresql/data
